name: react-native-square-reader-sdk
on: [push]
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: |
          yarn && yarn lint && yarn test && cd reader-sdk-react-native-quickstart && yarn
          yarn lint && cd ..
   build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:      
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-                
      - name: Install npm dependencies  
        uses: actions/checkout@v2
        with:
          SQUARE_READER_SDK_APPLICATION_ID: ${{secrets.SQUARE_READER_SDK_APPLICATION_ID}}
          SQUARE_READER_SDK_REPOSITORY_PASSWORD: ${{secrets.SQUARE_READER_SDK_REPOSITORY_PASSWORD}}
        env:
          SQUARE_READER_SDK_APPLICATION_ID: ${{secrets.SQUARE_READER_SDK_APPLICATION_ID}}
          SQUARE_READER_SDK_REPOSITORY_PASSWORD: ${{secrets.SQUARE_READER_SDK_REPOSITORY_PASSWORD}}  
      - run: |
          cd reader-sdk-react-native-quickstart && yarn  
          cd android
          ./gradlew clean build -PSQUARE_READER_SDK_APPLICATION_ID ${{ secrets.SQUARE_READER_SDK_APPLICATION_ID }} -PSQUARE_READER_SDK_REPOSITORY_PASSWORD ${{ secrets.SQUARE_READER_SDK_REPOSITORY_PASSWORD }}
  build-ios:
    needs: install-and-test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -vTORY_PASSWORD }}
